AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FormatStringToken:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/ComparableClamp:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false


Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*"

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FileOpen:
  Enabled: false

Metrics/BlockLength:
  Max: 60
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 80
  Exclude:
    - "lib/philiprehberger/toml_kit/parser.rb"
    - "lib/philiprehberger/toml_kit/serializer.rb"

Metrics/AbcSize:
  Max: 90
  Exclude:
    - "lib/philiprehberger/toml_kit/parser.rb"
    - "lib/philiprehberger/toml_kit/serializer.rb"

Metrics/CyclomaticComplexity:
  Max: 25
  Exclude:
    - "lib/philiprehberger/toml_kit/parser.rb"
    - "lib/philiprehberger/toml_kit/serializer.rb"
    - "lib/philiprehberger/toml_kit/comment_document.rb"

Metrics/PerceivedComplexity:
  Max: 25
  Exclude:
    - "lib/philiprehberger/toml_kit/parser.rb"
    - "lib/philiprehberger/toml_kit/serializer.rb"
    - "lib/philiprehberger/toml_kit/comment_document.rb"

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "lib/philiprehberger/toml_kit/parser.rb"
    - "lib/philiprehberger/toml_kit/serializer.rb"

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 8

Metrics/CollectionLiteralLength:
  Enabled: false

Layout/LineLength:
  Max: 140

Layout/EndOfLine:
  Enabled: false

Layout/BlockAlignment:
  Exclude:
    - "spec/**/*"

Lint/HashCompareByIdentity:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - "spec/**/*"

Lint/UnreachableLoop:
  Exclude:
    - "spec/**/*"

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/DuplicateHashKey:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Metrics/BlockNesting:
  Exclude:
    - "lib/philiprehberger/toml_kit/comment_document.rb"

Naming/PredicateMethod:
  Exclude:
    - "lib/philiprehberger/toml_kit/parser.rb"
    - "lib/philiprehberger/toml_kit/schema.rb"

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
